//! Roc Platform ABI
//!
//! This file defines Zig declarations for the direct symbol ABI used by a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must release owned refcounted arguments when done, using
//!   the release call named in each hosted symbol's doc comment below.
//! - Releasing a container releases its elements only when the container's own
//!   count reaches zero, which is what compiled Roc code does when it drops one
//!   it owns. Releasing the elements unconditionally double-frees them whenever
//!   the Roc caller still holds the container.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this file from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

const std = @import("std");
const builtin = @import("builtin");

/// Runtime representation of Roc's fixed-point `Dec` value.
///
/// `num` stores the decimal value scaled by 10^18.
pub const RocDec = extern struct {
    num: i128,
};

comptime {
    if (@sizeOf(RocDec) != 16) @compileError("RocDec size mismatch");
    if (@alignOf(RocDec) != 16) @compileError("RocDec alignment mismatch");
}

pub const RocU8x16 = @Vector(16, u8);
pub const RocI8x16 = @Vector(16, i8);
pub const RocU16x8 = @Vector(8, u16);
pub const RocI16x8 = @Vector(8, i16);
pub const RocU32x4 = @Vector(4, u32);
pub const RocI32x4 = @Vector(4, i32);
pub const RocU64x2 = @Vector(2, u64);
pub const RocI64x2 = @Vector(2, i64);
comptime {
    for (.{ RocU8x16, RocI8x16, RocU16x8, RocI16x8, RocU32x4, RocI32x4, RocU64x2, RocI64x2 }) |T| {
        if (@sizeOf(T) != 16) @compileError("Roc SIMD size mismatch");
        if (@alignOf(T) != 16) @compileError("Roc SIMD alignment mismatch");
    }
}

/// Runtime representation of an opaque `Box(T)` value.
pub const RocBox = ?*anyopaque;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
pub const RocHost = extern struct {
    env: *anyopaque,
    roc_alloc: *const fn (*RocHost, usize, usize) callconv(.c) ?*anyopaque,
    roc_dealloc: *const fn (*RocHost, *anyopaque, usize) callconv(.c) void,
    roc_realloc: *const fn (*RocHost, *anyopaque, usize, usize) callconv(.c) ?*anyopaque,
    roc_dbg: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_expect_failed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_crashed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
};

/// Private erased-callable function pointer stored in `RocErasedCallablePayload`.
///
/// The final `reuse` pointer is nullable. Non-null must be the callable data
/// pointer whose inline capture begins at `capture`; it transfers one owned
/// reference to the callee. The caller must not use or decref that ownership
/// unit after the call. The callee consumes it exactly once, whether or not the
/// result can reuse the allocation.
pub const RocErasedCallableFn = *const fn (*RocHost, ?[*]u8, ?[*]const u8, ?[*]u8, ?[*]u8, *?*const anyopaque) callconv(.c) void;

/// Final-drop callback for inline erased-callable captures.
pub const RocErasedCallableOnDrop = *const fn (?[*]u8, *RocHost) callconv(.c) void;

/// Payload header for `Box(function)`.
pub const RocErasedCallablePayload = extern struct {
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
};

/// Runtime representation of `Box(function)`.
pub const RocErasedCallable = ?[*]u8;

pub const roc_erased_callable_capture_alignment: usize = 16;
pub const roc_erased_callable_payload_alignment: usize = 16;
pub const roc_erased_callable_capture_offset: usize = std.mem.alignForward(usize, @sizeOf(RocErasedCallablePayload), roc_erased_callable_capture_alignment);

pub fn rocErasedCallablePayloadSize(capture_size: usize) usize {
    return roc_erased_callable_capture_offset + capture_size;
}

pub fn rocErasedCallablePayloadPtr(callable: RocErasedCallable) *RocErasedCallablePayload {
    return @ptrCast(@alignCast(callable orelse unreachable));
}

pub fn rocErasedCallableCapturePtr(callable: RocErasedCallable) ?[*]u8 {
    const data = callable orelse return null;
    return data + roc_erased_callable_capture_offset;
}

pub fn rocErasedCallableAllocate(
    roc_host: *RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
    capture_size: usize,
) RocErasedCallable {
    const ptr_width = @sizeOf(usize);
    const alignment = @max(ptr_width, roc_erased_callable_payload_alignment);
    const extra_bytes = @max(ptr_width, roc_erased_callable_payload_alignment);
    const length = extra_bytes + rocErasedCallablePayloadSize(capture_size);
    const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, length, alignment));
    const data = base + extra_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    const payload: *RocErasedCallablePayload = @ptrCast(@alignCast(data));
    payload.* = .{ .callable_fn_ptr = callable_fn_ptr, .on_drop = on_drop };
    return data;
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decrefBoxWith` and `freeBoxWith` free it after the callback.
pub const RocBoxPayloadDecref = *const fn (?*anyopaque, *RocHost) callconv(.c) void;

/// Increment the refcount of a boxed payload data pointer.
pub fn increfBox(data_ptr: ?*anyopaque, amount: isize) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
    _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
}

/// Allocate a Roc box and return a pointer to its payload data.
pub fn allocateBox(
    payload_size: usize,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: *RocHost,
) *anyopaque {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, header_bytes + payload_size, alloc_alignment));
    const data = base + header_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    return @ptrCast(data);
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
pub fn decrefBox(data_ptr: ?*anyopaque, roc_host: *RocHost) void {
    decrefBoxWith(data_ptr, @alignOf(usize), false, null, roc_host);
}

/// Increment a boxed function closure.
pub fn increfErasedCallable(callable: RocErasedCallable, amount: isize) void {
    const data = callable orelse return;
    increfBox(@ptrCast(data), amount);
}

/// Decrement a boxed function closure and run its capture drop callback on final release.
pub fn decrefErasedCallable(callable: RocErasedCallable, roc_host: *RocHost) void {
    const data = callable orelse return;
    decrefBoxWith(@ptrCast(data), roc_erased_callable_payload_alignment, false, &dropErasedCallablePayload, roc_host);
}

fn dropErasedCallablePayload(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const data = data_ptr orelse return;
    const callable: RocErasedCallable = @ptrCast(data);
    const payload = rocErasedCallablePayloadPtr(callable);
    if (payload.on_drop) |on_drop| {
        on_drop(rocErasedCallableCapturePtr(callable), roc_host);
    }
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
///
/// `payload_contains_refcounted` must match the value passed to `allocateBox`:
/// it determines the box header size, and is independent of whether a
/// `payload_decref` teardown callback is supplied. A host resource handle such
/// as `Box(U64)` holding a raw pointer has `payload_contains_refcounted = false`
/// even when it provides a teardown callback to free the underlying resource.
pub fn decrefBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA

    const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
    if (prev == 1) {
        if (payload_decref) |callback| callback(data_ptr, roc_host);
        freeBoxAllocation(data, payload_alignment, payload_contains_refcounted, roc_host);
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
///
/// See `decrefBoxWith` for the meaning of `payload_contains_refcounted`.
pub fn freeBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    if (payload_decref) |callback| callback(data_ptr, roc_host);
    freeBoxAllocation(data, payload_alignment, payload_contains_refcounted, roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn isUniqueBox(data_ptr: ?*anyopaque) bool {
    const data = boxDataPtr(data_ptr) orelse return true;
    const rc = boxRefcountPtr(data);
    return rc.* == 1;
}

fn boxDataPtr(data_ptr: ?*anyopaque) ?[*]u8 {
    const ptr = data_ptr orelse return null;
    return @ptrCast(ptr);
}

fn boxRefcountPtr(data: [*]u8) *isize {
    return @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
}

fn freeBoxAllocation(
    data: [*]u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: *RocHost,
) void {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: *anyopaque = @ptrFromInt(@intFromPtr(data) - header_bytes);
    roc_host.roc_dealloc(roc_host, base, alloc_alignment);
}

/// A Roc string value. Small strings (up to 23 bytes) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `std.math.maxInt(isize)` bytes: about 2 GiB on 32-bit targets
/// and 8 EiB on 64-bit targets.
pub const RocStr = extern struct {
    bytes: ?[*]u8,
    capacity_or_alloc_ptr: usize,
    length: usize,

    const Self = @This();
    const small_string_size = @sizeOf(RocStr);
    const small_str_max_length = small_string_size - 1;
    const small_str_bit: usize = @as(usize, @bitCast(@as(isize, std.math.minInt(isize))));
    const seamless_slice_tag: usize = 1;

    /// Return the string contents as a `[]const u8` slice.
    pub fn asSlice(self: *const Self) []const u8 {
        return self.asU8ptr()[0..self.len()];
    }

    /// Return the length of the string in bytes.
    pub fn len(self: Self) usize {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(&self))[@sizeOf(Self) - 1] ^ 0b1000_0000;
        } else {
            return self.length;
        }
    }

    /// Return true if the string has zero length.
    pub fn isEmpty(self: Self) bool {
        return self.len() == 0;
    }

    /// Return true if this string is stored inline (small string optimization).
    pub fn isSmallStr(self: Self) bool {
        return @as(isize, @bitCast(self.length)) < 0;
    }

    /// Return true if this string is a seamless slice into another allocation.
    pub fn isSeamlessSlice(self: Self) bool {
        return !self.isSmallStr() and (self.capacity_or_alloc_ptr & seamless_slice_tag) != 0;
    }

    /// Return a pointer to the raw UTF-8 bytes.
    pub fn asU8ptr(self: *const Self) [*]const u8 {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(self));
        } else {
            return @as([*]const u8, @ptrCast(self.bytes));
        }
    }

    /// Return an empty RocStr.
    pub fn empty() Self {
        return .{ .bytes = null, .capacity_or_alloc_ptr = 0, .length = small_str_bit };
    }

    /// Create a RocStr from a byte slice, using `roc_host` for heap allocation if needed.
    pub fn fromSlice(slice: []const u8, roc_host: *RocHost) Self {
        if (slice.len < small_string_size) {
            var result = Self.empty();
            const ptr: [*]u8 = @ptrCast(&result);
            @memcpy(ptr[0..slice.len], slice);
            ptr[@sizeOf(Self) - 1] = @as(u8, @intCast(slice.len)) | 0b1000_0000;
            return result;
        } else {
            const ptr_width = @sizeOf(usize);
            const extra_bytes = ptr_width;
            const total = extra_bytes + slice.len;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, @alignOf(usize)));
            const data_ptr = base + extra_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            @memcpy(data_ptr[0..slice.len], slice.ptr[0..slice.len]);
            return .{
                .bytes = data_ptr,
                .capacity_or_alloc_ptr = slice.len << 1,
                .length = slice.len,
            };
        }
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(self: Self, roc_host: *RocHost) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const data_addr = @intFromPtr(alloc_ptr);
        const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA—bytes are in read-only memory
        const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
        if (prev == 1) {
            const ptr_width = @sizeOf(usize);
            const base: *anyopaque = @ptrFromInt(data_addr - ptr_width);
            roc_host.roc_dealloc(roc_host, base, @alignOf(usize));
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(self: Self, amount: isize) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
        _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn isUnique(self: Self) bool {
        if (self.isSmallStr()) return true;
        const alloc_ptr = self.getAllocationPtr() orelse return true;
        const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA—treated as unique
        return rc.* == 1;
    }

    fn getAllocationPtr(self: Self) ?[*]u8 {
        if (self.isSeamlessSlice()) {
            return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~seamless_slice_tag));
        } else {
            return self.bytes;
        }
    }
};

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `elements_refcounted` is true (the default), an extra `ptr_width` bytes
/// are reserved in the allocation header for the element count, matching the Roc
/// runtime's `allocateWithRefcount` layout. Set to `false` for lists of
/// non-refcounted primitives (e.g. `U8`, `I32`).
pub fn RocList(comptime T: type) type {
    return RocListWith(T, true);
}

/// Parameterized list constructor; use `RocList(T)` for refcounted elements.
pub fn RocListWith(comptime T: type, comptime elements_refcounted: bool) type {
    return extern struct {
        elements_ptr: ?[*]T,
        length: usize,
        capacity_or_alloc_ptr: usize,

        const Self = @This();
        const ptr_width = @sizeOf(usize);
        const required_space: usize = if (elements_refcounted) (2 * ptr_width) else ptr_width;
        const header_bytes = @max(required_space, @alignOf(T));
        const alloc_align = @max(ptr_width, @alignOf(T));

        /// Return the list elements as a `[]const T` slice.
        pub fn items(self: Self) []const T {
            if (self.elements_ptr) |ptr| return ptr[0..self.length];
            return &[_]T{};
        }

        /// Return every initialized element in the backing allocation.
        pub fn allocationItems(self: Self) []const T {
            const alloc_ptr = self.getAllocationPtr() orelse return &[_]T{};
            const count = self.allocationElementCount();
            const ptr: [*]const T = @ptrCast(@alignCast(alloc_ptr));
            return ptr[0..count];
        }

        /// Return the number of elements in the list.
        pub fn len(self: Self) usize {
            return self.length;
        }

        /// Return true if the list has zero elements.
        pub fn isEmpty(self: Self) bool {
            return self.length == 0;
        }

        /// Return true if this list is a seamless slice into another allocation.
        /// Slices share the rc slot with their backing allocation; the alloc ptr is
        /// encoded in `capacity_or_alloc_ptr` with the low bit set.
        pub fn isSeamlessSlice(self: Self) bool {
            return (self.capacity_or_alloc_ptr & 1) != 0;
        }

        /// Return an empty RocList.
        pub fn empty() Self {
            return .{ .elements_ptr = null, .length = 0, .capacity_or_alloc_ptr = 0 };
        }

        /// Resolve `self` to the start of its backing allocation (the element block
        /// just after the rc slot). Returns `null` for empty lists. Handles both
        /// whole-backing and seamless-slice forms.
        fn getAllocationPtr(self: Self) ?[*]u8 {
            if (self.isSeamlessSlice()) {
                return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~@as(usize, 1)));
            }
            const ptr = self.elements_ptr orelse return null;
            return @ptrCast(ptr);
        }

        fn allocationElementCount(self: Self) usize {
            if (self.isSeamlessSlice() and elements_refcounted) {
                const alloc_ptr = self.getAllocationPtr() orelse return 0;
                const ptr: [*]const usize = @ptrCast(@alignCast(alloc_ptr));
                return (ptr - 2)[0];
            }
            return self.length;
        }

        /// Allocate a new list with space for `length` elements.
        pub fn allocate(length: usize, roc_host: *RocHost) Self {
            if (length == 0) return empty();
            const data_bytes = length * @sizeOf(T);
            const total = data_bytes + header_bytes;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, alloc_align));
            const data_ptr = base + header_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            if (elements_refcounted) {
                const count: *usize = @ptrFromInt(@intFromPtr(data_ptr) - (2 * @sizeOf(usize)));
                count.* = length;
            }
            return .{
                .elements_ptr = @ptrCast(@alignCast(data_ptr)),
                .length = length,
                .capacity_or_alloc_ptr = length << 1,
            };
        }

        /// Create a RocList from a slice, copying elements into a new allocation.
        pub fn fromSlice(slice: []const T, roc_host: *RocHost) Self {
            if (slice.len == 0) return empty();
            const list = allocate(slice.len, roc_host);
            const dest: [*]u8 = @ptrCast(list.elements_ptr.?);
            const src: [*]const u8 = @ptrCast(slice.ptr);
            @memcpy(dest[0 .. slice.len * @sizeOf(T)], src[0 .. slice.len * @sizeOf(T)]);
            return list;
        }

        /// Drop this reference to the list allocation, freeing it when this was
        /// the last one.
        ///
        /// Shallow: it never touches the elements. To release an owned list whose
        /// elements are refcounted, call that list's generated `decrefListOf...`
        /// helper instead, which drops the elements when this reference is the
        /// last one and then calls this.
        pub fn decref(self: Self, roc_host: *RocHost) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const data_addr = @intFromPtr(alloc_ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA—bytes are in read-only memory
            const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
            if (prev == 1) {
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                roc_host.roc_dealloc(roc_host, base, alloc_align);
            }
        }

        /// Recursively release this list and its elements.
        ///
        /// The reference-count decrement claims the final reference atomically
        /// before reading any elements, so concurrent releases cannot skip or
        /// duplicate element teardown.
        pub fn deinit(self: Self, roc_host: *RocHost) void {
            const ItemRelease = if (elements_refcounted) rocReleasePolicy(T) else RocNoopRelease(T);
            self.deinitWith(ItemRelease, roc_host);
        }

        /// Recursively release with an explicit compiler-generated item policy.
        pub fn deinitWith(self: Self, comptime ItemRelease: type, roc_host: *RocHost) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const data_addr = @intFromPtr(alloc_ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA—elements are in read-only memory
            const prev = @atomicRmw(isize, rc, .Sub, 1, .acq_rel);
            if (prev == 1) {
                if (elements_refcounted) {
                    for (self.allocationItems()) |item| {
                        ItemRelease.release(item, roc_host);
                    }
                }
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                roc_host.roc_dealloc(roc_host, base, alloc_align);
            }
        }

        /// Increment the reference count by `amount`.
        pub fn incref(self: Self, amount: isize) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
            _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
        }

        /// Return true if this list has a reference count of exactly one.
        pub fn isUnique(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return true;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA—treated as unique
            return rc.* == 1;
        }

        /// Return true if this list's allocation has exactly one counted ref.
        pub fn hasOneRef(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return false;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            return rc.* == 1;
        }
    };
}

pub fn RocNoopRelease(comptime T: type) type {
    return struct {
        pub fn release(value: T, roc_host: *RocHost) void {
            _ = value;
            _ = roc_host;
        }
    };
}

/// A zero-runtime-storage release policy for one Roc string.
pub const RocStrRelease = struct {
    pub fn release(value: RocStr, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

/// Compose a list release policy from its item release policy.
pub fn RocListRelease(comptime ListType: type, comptime ItemRelease: type) type {
    return struct {
        pub fn release(value: ListType, roc_host: *RocHost) void {
            value.deinitWith(ItemRelease, roc_host);
        }
    };
}

/// Release only a list spine whose elements contain no Roc references.
pub fn RocListSpineRelease(comptime ListType: type) type {
    return struct {
        pub fn release(value: ListType, roc_host: *RocHost) void {
            value.decref(roc_host);
        }
    };
}

pub const RocErasedCallableRelease = struct {
    pub fn release(value: RocErasedCallable, roc_host: *RocHost) void {
        decrefErasedCallable(value, roc_host);
    }
};

pub fn RocBoxRelease(comptime ValueType: type, comptime PayloadType: type, comptime PayloadRelease: type) type {
    return struct {
        fn releasePayload(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
            const payload: *PayloadType = @ptrCast(@alignCast(data_ptr orelse return));
            PayloadRelease.release(payload.*, roc_host);
        }

        pub fn release(value: ValueType, roc_host: *RocHost) void {
            decrefBoxWith(@ptrCast(value), @alignOf(PayloadType), true, &releasePayload, roc_host);
        }
    };
}

pub fn RocBoxSpineRelease(comptime ValueType: type, comptime PayloadType: type) type {
    return struct {
        pub fn release(value: ValueType, roc_host: *RocHost) void {
            decrefBoxWith(@ptrCast(value), @alignOf(PayloadType), false, null, roc_host);
        }
    };
}

/// Minimal I/O abstraction for Roc platform hosts.
///
/// Provides stderr output and fatal-error handling that can be routed
/// to different backends (POSIX, freestanding/WASM, custom).
///
/// Use `RocIo.default()` for most platforms; inject a custom vtable for
/// environments without POSIX stdio (e.g. WASM freestanding).
pub const RocIo = struct {
    ctx: ?*anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        /// Write to stderr. Best-effort: errors are silently ignored.
        writeStderr: *const fn (?*anyopaque, []const u8) void,
        /// Terminate the process or trap. Must not return.
        onFatal: *const fn (?*anyopaque) noreturn,
    };

    /// Write `data` to stderr (best-effort).
    pub fn writeStderr(self: RocIo, data: []const u8) void {
        self.vtable.writeStderr(self.ctx, data);
    }

    /// Terminate the process or trap. Does not return.
    pub fn onFatal(self: RocIo) noreturn {
        self.vtable.onFatal(self.ctx);
    }

    /// Native (POSIX) implementation: writes to stderr, exits with code 1.
    pub fn native() RocIo {
        return .{ .ctx = null, .vtable = &native_vtable };
    }

    /// Freestanding implementation: no-op stderr, @trap() on fatal.
    pub fn freestanding() RocIo {
        return .{ .ctx = null, .vtable = &freestanding_vtable };
    }

    /// Select the appropriate implementation for the current build target.
    pub fn default() RocIo {
        if (comptime builtin.os.tag == .freestanding) {
            return freestanding();
        }
        return native();
    }

    fn nativeWriteStderr(_: ?*anyopaque, data: []const u8) void {
        std.Io.File.stderr().writeStreamingAll(std.Io.Threaded.global_single_threaded.io(), data) catch {};
    }

    fn nativeOnFatal(_: ?*anyopaque) noreturn {
        std.process.exit(1);
    }

    fn freestandingWriteStderr(_: ?*anyopaque, _: []const u8) void {}

    fn freestandingOnFatal(_: ?*anyopaque) noreturn {
        @trap();
    }

    const native_vtable: VTable = .{
        .writeStderr = &nativeWriteStderr,
        .onFatal = &nativeOnFatal,
    };

    const freestanding_vtable: VTable = .{
        .writeStderr = &freestandingWriteStderr,
        .onFatal = &freestandingOnFatal,
    };
};

/// Host environment passed to the Roc runtime.
///
/// Bundles the allocator and I/O backend used by DefaultAllocators
/// and DefaultHandlers.
pub const RocEnv = struct {
    allocator: std.mem.Allocator,
    roc_io: RocIo,
};

/// Element type for __AnonStruct_f14e2b8a8783e7e5
pub const __AnonStruct_f14e2b8a8783e7e5 = if (@sizeOf(usize) == 4) extern struct {
    @"tasks": RocList(__AnonStruct_d1555daa8670bff1),
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        decrefListOf__AnonStruct_d1555daa8670bff1(value.@"tasks", roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"tasks".incref(amount);
    }
} else extern struct {
    @"tasks": RocList(__AnonStruct_d1555daa8670bff1),
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        decrefListOf__AnonStruct_d1555daa8670bff1(value.@"tasks", roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"tasks".incref(amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct_f14e2b8a8783e7e5) != 24) @compileError("__AnonStruct_f14e2b8a8783e7e5 size mismatch");
        if (@alignOf(__AnonStruct_f14e2b8a8783e7e5) != 8) @compileError("__AnonStruct_f14e2b8a8783e7e5 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct_f14e2b8a8783e7e5) != 12) @compileError("__AnonStruct_f14e2b8a8783e7e5 size mismatch");
        if (@alignOf(__AnonStruct_f14e2b8a8783e7e5) != 4) @compileError("__AnonStruct_f14e2b8a8783e7e5 alignment mismatch");
    }
}

/// Element type for __AnonStruct_d1555daa8670bff1
pub const __AnonStruct_d1555daa8670bff1 = if (@sizeOf(usize) == 4) extern struct {
    @"id": u64,
    @"action": __AnonStruct_d0dfc1ec817c4484,
    @"cwd": RocStr,
    @"depends_on": RocListWith(u64, false),
    @"description": RocStr,
    @"env": RocList(__AnonStruct_77eaba63dfee299d),
    @"inputs": RocList(RocStr),
    @"outputs": RocList(RocStr),
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        value.@"action".decref(roc_host);
        value.@"cwd".decref(roc_host);
        value.@"depends_on".decref(roc_host);
        value.@"description".decref(roc_host);
        decrefListOf__AnonStruct_77eaba63dfee299d(value.@"env", roc_host);
        decrefListOfStr(value.@"inputs", roc_host);
        decrefListOfStr(value.@"outputs", roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"action".incref(amount);
        value.@"cwd".incref(amount);
        value.@"depends_on".incref(amount);
        value.@"description".incref(amount);
        value.@"env".incref(amount);
        value.@"inputs".incref(amount);
        value.@"outputs".incref(amount);
    }
} else extern struct {
    @"id": u64,
    @"action": __AnonStruct_d0dfc1ec817c4484,
    @"cwd": RocStr,
    @"depends_on": RocListWith(u64, false),
    @"description": RocStr,
    @"env": RocList(__AnonStruct_77eaba63dfee299d),
    @"inputs": RocList(RocStr),
    @"outputs": RocList(RocStr),
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        value.@"action".decref(roc_host);
        value.@"cwd".decref(roc_host);
        value.@"depends_on".decref(roc_host);
        value.@"description".decref(roc_host);
        decrefListOf__AnonStruct_77eaba63dfee299d(value.@"env", roc_host);
        decrefListOfStr(value.@"inputs", roc_host);
        decrefListOfStr(value.@"outputs", roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"action".incref(amount);
        value.@"cwd".incref(amount);
        value.@"depends_on".incref(amount);
        value.@"description".incref(amount);
        value.@"env".incref(amount);
        value.@"inputs".incref(amount);
        value.@"outputs".incref(amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct_d1555daa8670bff1) != 200) @compileError("__AnonStruct_d1555daa8670bff1 size mismatch");
        if (@alignOf(__AnonStruct_d1555daa8670bff1) != 8) @compileError("__AnonStruct_d1555daa8670bff1 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct_d1555daa8670bff1) != 104) @compileError("__AnonStruct_d1555daa8670bff1 size mismatch");
        if (@alignOf(__AnonStruct_d1555daa8670bff1) != 8) @compileError("__AnonStruct_d1555daa8670bff1 alignment mismatch");
    }
}

/// Element type for __AnonStruct_d0dfc1ec817c4484
pub const __AnonStruct_d0dfc1ec817c4484 = if (@sizeOf(usize) == 4) extern struct {
    @"args": RocList(RocStr),
    @"program": RocStr,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        decrefListOfStr(value.@"args", roc_host);
        value.@"program".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"args".incref(amount);
        value.@"program".incref(amount);
    }
} else extern struct {
    @"args": RocList(RocStr),
    @"program": RocStr,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        decrefListOfStr(value.@"args", roc_host);
        value.@"program".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"args".incref(amount);
        value.@"program".incref(amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct_d0dfc1ec817c4484) != 48) @compileError("__AnonStruct_d0dfc1ec817c4484 size mismatch");
        if (@alignOf(__AnonStruct_d0dfc1ec817c4484) != 8) @compileError("__AnonStruct_d0dfc1ec817c4484 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct_d0dfc1ec817c4484) != 24) @compileError("__AnonStruct_d0dfc1ec817c4484 size mismatch");
        if (@alignOf(__AnonStruct_d0dfc1ec817c4484) != 4) @compileError("__AnonStruct_d0dfc1ec817c4484 alignment mismatch");
    }
}

/// Element type for __AnonStruct_77eaba63dfee299d
pub const __AnonStruct_77eaba63dfee299d = if (@sizeOf(usize) == 4) extern struct {
    @"_0": RocStr,
    @"_1": RocStr,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        value.@"_0".decref(roc_host);
        value.@"_1".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"_0".incref(amount);
        value.@"_1".incref(amount);
    }
} else extern struct {
    @"_0": RocStr,
    @"_1": RocStr,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        value.@"_0".decref(roc_host);
        value.@"_1".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"_0".incref(amount);
        value.@"_1".incref(amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct_77eaba63dfee299d) != 48) @compileError("__AnonStruct_77eaba63dfee299d size mismatch");
        if (@alignOf(__AnonStruct_77eaba63dfee299d) != 8) @compileError("__AnonStruct_77eaba63dfee299d alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct_77eaba63dfee299d) != 24) @compileError("__AnonStruct_77eaba63dfee299d size mismatch");
        if (@alignOf(__AnonStruct_77eaba63dfee299d) != 4) @compileError("__AnonStruct_77eaba63dfee299d alignment mismatch");
    }
}

/// Tag discriminant for Try.
pub const HostRun_graphResultTag = enum(u8) {
    @"Err" = 0,
    @"Ok" = 1,
};

/// Payload union for Try.
pub const HostRun_graphResultPayload = extern union {
        @"err": RocStr,
        @"ok": [0]u8,
};

/// Tag union: Try
pub const HostRun_graphResult = if (@sizeOf(usize) == 4) extern struct {
    payload: [12]u8 align(4),
    tag: HostRun_graphResultTag,
    pub fn payload_err(self: *const @This()) RocStr {
        const ptr: *const RocStr = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostRun_graphResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostRun_graphResult(self, amount);
    }
} else extern struct {
    payload: HostRun_graphResultPayload,
    tag: HostRun_graphResultTag,
    pub fn payload_err(self: *const @This()) RocStr {
        return self.payload.@"err";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostRun_graphResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostRun_graphResult(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostRun_graphResult) != 32) @compileError("HostRun_graphResult size mismatch");
        if (@alignOf(HostRun_graphResult) != 8) @compileError("HostRun_graphResult alignment mismatch");
        if (@offsetOf(HostRun_graphResult, "tag") != 24) @compileError("HostRun_graphResult tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(HostRun_graphResult) != 16) @compileError("HostRun_graphResult size mismatch");
        if (@alignOf(HostRun_graphResult) != 4) @compileError("HostRun_graphResult alignment mismatch");
        if (@offsetOf(HostRun_graphResult, "tag") != 12) @compileError("HostRun_graphResult tag offset mismatch");
    }
}

/// Tag discriminant for Try.
pub const HostCmd_execResultTag = enum(u8) {
    @"Err" = 0,
    @"Ok" = 1,
};

/// Payload union for Try.
pub const HostCmd_execResultPayload = extern union {
        @"err": CmdErrOrNonZeroExit,
        @"ok": [0]u8,
};

/// Tag union: Try
pub const HostCmd_execResult = if (@sizeOf(usize) == 4) extern struct {
    payload: [16]u8 align(4),
    tag: HostCmd_execResultTag,
    pub fn payload_err(self: *const @This()) CmdErrOrNonZeroExit {
        const ptr: *const CmdErrOrNonZeroExit = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostCmd_execResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostCmd_execResult(self, amount);
    }
} else extern struct {
    payload: HostCmd_execResultPayload,
    tag: HostCmd_execResultTag,
    pub fn payload_err(self: *const @This()) CmdErrOrNonZeroExit {
        return self.payload.@"err";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostCmd_execResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostCmd_execResult(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostCmd_execResult) != 40) @compileError("HostCmd_execResult size mismatch");
        if (@alignOf(HostCmd_execResult) != 8) @compileError("HostCmd_execResult alignment mismatch");
        if (@offsetOf(HostCmd_execResult, "tag") != 32) @compileError("HostCmd_execResult tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(HostCmd_execResult) != 20) @compileError("HostCmd_execResult size mismatch");
        if (@alignOf(HostCmd_execResult) != 4) @compileError("HostCmd_execResult alignment mismatch");
        if (@offsetOf(HostCmd_execResult, "tag") != 16) @compileError("HostCmd_execResult tag offset mismatch");
    }
}

/// Tag discriminant for CmdErrOrNonZeroExit.
pub const CmdErrOrNonZeroExitTag = enum(u8) {
    @"CmdErr" = 0,
    @"NonZeroExit" = 1,
};

/// Payload union for CmdErrOrNonZeroExit.
pub const CmdErrOrNonZeroExitPayload = extern union {
        @"cmd_err": RocStr,
        @"non_zero_exit": i32,
};

/// Tag union: CmdErrOrNonZeroExit
pub const CmdErrOrNonZeroExit = if (@sizeOf(usize) == 4) extern struct {
    payload: [12]u8 align(4),
    tag: CmdErrOrNonZeroExitTag,
    pub fn payload_cmd_err(self: *const @This()) RocStr {
        const ptr: *const RocStr = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_non_zero_exit(self: *const @This()) i32 {
        const ptr: *const i32 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefCmdErrOrNonZeroExit(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfCmdErrOrNonZeroExit(self, amount);
    }
} else extern struct {
    payload: CmdErrOrNonZeroExitPayload,
    tag: CmdErrOrNonZeroExitTag,
    pub fn payload_cmd_err(self: *const @This()) RocStr {
        return self.payload.@"cmd_err";
    }
    pub fn payload_non_zero_exit(self: *const @This()) i32 {
        return self.payload.@"non_zero_exit";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefCmdErrOrNonZeroExit(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfCmdErrOrNonZeroExit(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(CmdErrOrNonZeroExit) != 32) @compileError("CmdErrOrNonZeroExit size mismatch");
        if (@alignOf(CmdErrOrNonZeroExit) != 8) @compileError("CmdErrOrNonZeroExit alignment mismatch");
        if (@offsetOf(CmdErrOrNonZeroExit, "tag") != 24) @compileError("CmdErrOrNonZeroExit tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(CmdErrOrNonZeroExit) != 16) @compileError("CmdErrOrNonZeroExit size mismatch");
        if (@alignOf(CmdErrOrNonZeroExit) != 4) @compileError("CmdErrOrNonZeroExit alignment mismatch");
        if (@offsetOf(CmdErrOrNonZeroExit, "tag") != 12) @compileError("CmdErrOrNonZeroExit tag offset mismatch");
    }
}

/// Tag discriminant for Try.
pub const HostFile_read_bytesResultTag = enum(u8) {
    @"Err" = 0,
    @"Ok" = 1,
};

/// Payload union for Try.
pub const HostFile_read_bytesResultPayload = extern union {
        @"err": RocStr,
        @"ok": RocListWith(u8, false),
};

/// Tag union: Try
pub const HostFile_read_bytesResult = if (@sizeOf(usize) == 4) extern struct {
    payload: [12]u8 align(4),
    tag: HostFile_read_bytesResultTag,
    pub fn payload_err(self: *const @This()) RocStr {
        const ptr: *const RocStr = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_ok(self: *const @This()) RocListWith(u8, false) {
        const ptr: *const RocListWith(u8, false) = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostFile_read_bytesResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostFile_read_bytesResult(self, amount);
    }
} else extern struct {
    payload: HostFile_read_bytesResultPayload,
    tag: HostFile_read_bytesResultTag,
    pub fn payload_err(self: *const @This()) RocStr {
        return self.payload.@"err";
    }
    pub fn payload_ok(self: *const @This()) RocListWith(u8, false) {
        return self.payload.@"ok";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostFile_read_bytesResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostFile_read_bytesResult(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostFile_read_bytesResult) != 32) @compileError("HostFile_read_bytesResult size mismatch");
        if (@alignOf(HostFile_read_bytesResult) != 8) @compileError("HostFile_read_bytesResult alignment mismatch");
        if (@offsetOf(HostFile_read_bytesResult, "tag") != 24) @compileError("HostFile_read_bytesResult tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(HostFile_read_bytesResult) != 16) @compileError("HostFile_read_bytesResult size mismatch");
        if (@alignOf(HostFile_read_bytesResult) != 4) @compileError("HostFile_read_bytesResult alignment mismatch");
        if (@offsetOf(HostFile_read_bytesResult, "tag") != 12) @compileError("HostFile_read_bytesResult tag offset mismatch");
    }
}

/// Tag discriminant for Try.
pub const HostFile_write_bytesResultTag = enum(u8) {
    @"Err" = 0,
    @"Ok" = 1,
};

/// Payload union for Try.
pub const HostFile_write_bytesResultPayload = extern union {
        @"err": RocStr,
        @"ok": [0]u8,
};

/// Tag union: Try
pub const HostFile_write_bytesResult = if (@sizeOf(usize) == 4) extern struct {
    payload: [12]u8 align(4),
    tag: HostFile_write_bytesResultTag,
    pub fn payload_err(self: *const @This()) RocStr {
        const ptr: *const RocStr = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostFile_write_bytesResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostFile_write_bytesResult(self, amount);
    }
} else extern struct {
    payload: HostFile_write_bytesResultPayload,
    tag: HostFile_write_bytesResultTag,
    pub fn payload_err(self: *const @This()) RocStr {
        return self.payload.@"err";
    }
    /// Recursively decrement Roc-owned payloads.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        decrefHostFile_write_bytesResult(self, roc_host);
    }

    /// Increment Roc-owned payloads.
    pub fn incref(self: @This(), amount: isize) void {
        increfHostFile_write_bytesResult(self, amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostFile_write_bytesResult) != 32) @compileError("HostFile_write_bytesResult size mismatch");
        if (@alignOf(HostFile_write_bytesResult) != 8) @compileError("HostFile_write_bytesResult alignment mismatch");
        if (@offsetOf(HostFile_write_bytesResult, "tag") != 24) @compileError("HostFile_write_bytesResult tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(HostFile_write_bytesResult) != 16) @compileError("HostFile_write_bytesResult size mismatch");
        if (@alignOf(HostFile_write_bytesResult) != 4) @compileError("HostFile_write_bytesResult alignment mismatch");
        if (@offsetOf(HostFile_write_bytesResult, "tag") != 12) @compileError("HostFile_write_bytesResult tag offset mismatch");
    }
}

/// Arguments for Host.run_graph!
/// Roc signature: { tasks : List({ action : [Cmd({ args : List(Str), program : Str })], cwd : Str, depends_on : List(U64), description : Str, env : List((Str, Str)), id : U64, inputs : List(Str), outputs : List(Str) }) } => Try({}, [BuildFailed(Str)])
/// Refcounted fields are owned by the hosted function.
pub const HostRun_graphArgs = if (@sizeOf(usize) == 4) extern struct {
    @"tasks": RocList(__AnonStruct_d1555daa8670bff1),
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        decrefListOf__AnonStruct_d1555daa8670bff1(value.@"tasks", roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"tasks".incref(amount);
    }
} else extern struct {
    @"tasks": RocList(__AnonStruct_d1555daa8670bff1),
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        decrefListOf__AnonStruct_d1555daa8670bff1(value.@"tasks", roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"tasks".incref(amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostRun_graphArgs) != 24) @compileError("HostRun_graphArgs size mismatch");
        if (@alignOf(HostRun_graphArgs) != 8) @compileError("HostRun_graphArgs alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(HostRun_graphArgs) != 12) @compileError("HostRun_graphArgs size mismatch");
        if (@alignOf(HostRun_graphArgs) != 4) @compileError("HostRun_graphArgs alignment mismatch");
    }
}

/// Arguments for Host.log_info!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
pub const HostLog_infoArgs = extern struct {
    arg0: RocStr,
};

/// Arguments for Host.log_warn!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
pub const HostLog_warnArgs = extern struct {
    arg0: RocStr,
};

/// Arguments for Host.log_error!
/// Roc signature: Str => {}
/// Refcounted fields are owned by the hosted function.
pub const HostLog_errorArgs = extern struct {
    arg0: RocStr,
};

/// Arguments for Host.cmd_exec!
/// Roc signature: { args : List(Str), program : Str } => Try({}, [CmdErr(Str), NonZeroExit(I32)])
/// Refcounted fields are owned by the hosted function.
pub const HostCmd_execArgs = if (@sizeOf(usize) == 4) extern struct {
    @"args": RocList(RocStr),
    @"program": RocStr,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        decrefListOfStr(value.@"args", roc_host);
        value.@"program".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"args".incref(amount);
        value.@"program".incref(amount);
    }
} else extern struct {
    @"args": RocList(RocStr),
    @"program": RocStr,
    /// Recursively decrement Roc-owned fields.
    pub fn decref(self: @This(), roc_host: *RocHost) void {
        const value = self;
        decrefListOfStr(value.@"args", roc_host);
        value.@"program".decref(roc_host);
    }

    /// Increment Roc-owned fields.
    pub fn incref(self: @This(), amount: isize) void {
        const value = self;
        value.@"args".incref(amount);
        value.@"program".incref(amount);
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(HostCmd_execArgs) != 48) @compileError("HostCmd_execArgs size mismatch");
        if (@alignOf(HostCmd_execArgs) != 8) @compileError("HostCmd_execArgs alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(HostCmd_execArgs) != 24) @compileError("HostCmd_execArgs size mismatch");
        if (@alignOf(HostCmd_execArgs) != 4) @compileError("HostCmd_execArgs alignment mismatch");
    }
}

/// Arguments for Host.file_read_bytes!
/// Roc signature: Str => Try(List(U8), [IoErr(Str)])
/// Refcounted fields are owned by the hosted function.
pub const HostFile_read_bytesArgs = extern struct {
    arg0: RocStr,
};

/// Arguments for Host.file_write_bytes!
/// Roc signature: Str, List(U8) => Try({}, [IoErr(Str)])
/// Refcounted fields are owned by the hosted function.
pub const HostFile_write_bytesArgs = extern struct {
    arg0: RocStr,
    arg1: RocListWith(u8, false),
};

/// Arguments for Host.path_exists!
/// Roc signature: Str => Bool
/// Refcounted fields are owned by the hosted function.
pub const HostPath_existsArgs = extern struct {
    arg0: RocStr,
};

// Platform Type Aliases

pub const HostRun_graphArg0 = __AnonStruct_f14e2b8a8783e7e5;
pub const HostRun_graphArg0Tasks = __AnonStruct_d1555daa8670bff1;
pub const Cmd = __AnonStruct_d0dfc1ec817c4484;
pub const CmdCmd = __AnonStruct_d0dfc1ec817c4484;
pub const HostRun_graphArg0TasksEnv = __AnonStruct_77eaba63dfee299d;
pub const HostCmd_execArg0 = __AnonStruct_d0dfc1ec817c4484;
pub const HostCmd_execErr = CmdErrOrNonZeroExit;
pub const HostCmd_execErrPayload = CmdErrOrNonZeroExitPayload;
pub const HostCmd_execErrTag = CmdErrOrNonZeroExitTag;

// Generated Refcount Helpers

fn decrefHostRun_graphResult(value: HostRun_graphResult, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().decref(roc_host);
        },
        .@"Ok" => {},
    }
}

fn increfHostRun_graphResult(value: HostRun_graphResult, amount: isize) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().incref(amount);
        },
        .@"Ok" => {},
    }
}

pub const HostRun_graphResultRelease = struct {
    pub fn release(value: HostRun_graphResult, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

pub const __AnonStruct_f14e2b8a8783e7e5Release = struct {
    pub fn release(value: __AnonStruct_f14e2b8a8783e7e5, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

pub const __AnonStruct_d1555daa8670bff1Release = struct {
    pub fn release(value: __AnonStruct_d1555daa8670bff1, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

pub const __AnonStruct_d0dfc1ec817c4484Release = struct {
    pub fn release(value: __AnonStruct_d0dfc1ec817c4484, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

pub const __AnonStruct_77eaba63dfee299dRelease = struct {
    pub fn release(value: __AnonStruct_77eaba63dfee299d, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

fn decrefHostCmd_execResult(value: HostCmd_execResult, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().decref(roc_host);
        },
        .@"Ok" => {},
    }
}

fn increfHostCmd_execResult(value: HostCmd_execResult, amount: isize) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().incref(amount);
        },
        .@"Ok" => {},
    }
}

pub const HostCmd_execResultRelease = struct {
    pub fn release(value: HostCmd_execResult, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

fn decrefCmdErrOrNonZeroExit(value: CmdErrOrNonZeroExit, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"CmdErr" => {
        value.payload_cmd_err().decref(roc_host);
        },
        .@"NonZeroExit" => {},
    }
}

fn increfCmdErrOrNonZeroExit(value: CmdErrOrNonZeroExit, amount: isize) void {
    switch (value.tag) {
        .@"CmdErr" => {
        value.payload_cmd_err().incref(amount);
        },
        .@"NonZeroExit" => {},
    }
}

pub const CmdErrOrNonZeroExitRelease = struct {
    pub fn release(value: CmdErrOrNonZeroExit, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

fn decrefHostFile_read_bytesResult(value: HostFile_read_bytesResult, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().decref(roc_host);
        },
        .@"Ok" => {
        value.payload_ok().decref(roc_host);
        },
    }
}

fn increfHostFile_read_bytesResult(value: HostFile_read_bytesResult, amount: isize) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().incref(amount);
        },
        .@"Ok" => {
        value.payload_ok().incref(amount);
        },
    }
}

pub const HostFile_read_bytesResultRelease = struct {
    pub fn release(value: HostFile_read_bytesResult, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

fn decrefHostFile_write_bytesResult(value: HostFile_write_bytesResult, roc_host: *RocHost) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().decref(roc_host);
        },
        .@"Ok" => {},
    }
}

fn increfHostFile_write_bytesResult(value: HostFile_write_bytesResult, amount: isize) void {
    switch (value.tag) {
        .@"Err" => {
        value.payload_err().incref(amount);
        },
        .@"Ok" => {},
    }
}

pub const HostFile_write_bytesResultRelease = struct {
    pub fn release(value: HostFile_write_bytesResult, roc_host: *RocHost) void {
        value.decref(roc_host);
    }
};

/// Release one owned reference to a `RocList(__AnonStruct_d1555daa8670bff1)`.
///
/// The allocation's final reference is claimed atomically before any element
/// is read, so concurrent owners cannot skip or duplicate element teardown.
pub fn decrefListOf__AnonStruct_d1555daa8670bff1(value: RocList(__AnonStruct_d1555daa8670bff1), roc_host: *RocHost) void {
    value.deinitWith(__AnonStruct_d1555daa8670bff1Release, roc_host);
}

/// Release one owned reference to a `RocList(RocStr)`.
///
/// The allocation's final reference is claimed atomically before any element
/// is read, so concurrent owners cannot skip or duplicate element teardown.
pub fn decrefListOfStr(value: RocList(RocStr), roc_host: *RocHost) void {
    value.deinitWith(RocStrRelease, roc_host);
}

/// Release one owned reference to a `RocList(__AnonStruct_77eaba63dfee299d)`.
///
/// The allocation's final reference is claimed atomically before any element
/// is read, so concurrent owners cannot skip or duplicate element teardown.
pub fn decrefListOf__AnonStruct_77eaba63dfee299d(value: RocList(__AnonStruct_77eaba63dfee299d), roc_host: *RocHost) void {
    value.deinitWith(__AnonStruct_77eaba63dfee299dRelease, roc_host);
}


fn rocReleasePolicy(comptime T: type) type {
    if (T == RocStr) return RocStrRelease;
    if (T == HostRun_graphResult) return HostRun_graphResultRelease;
    if (T == __AnonStruct_f14e2b8a8783e7e5) return __AnonStruct_f14e2b8a8783e7e5Release;
    if (T == RocList(__AnonStruct_d1555daa8670bff1)) return RocListRelease(RocList(__AnonStruct_d1555daa8670bff1), __AnonStruct_d1555daa8670bff1Release);
    if (T == __AnonStruct_d1555daa8670bff1) return __AnonStruct_d1555daa8670bff1Release;
    if (T == __AnonStruct_d0dfc1ec817c4484) return __AnonStruct_d0dfc1ec817c4484Release;
    if (T == RocList(RocStr)) return RocListRelease(RocList(RocStr), RocStrRelease);
    if (T == RocListWith(u64, false)) return RocListSpineRelease(RocListWith(u64, false));
    if (T == RocList(__AnonStruct_77eaba63dfee299d)) return RocListRelease(RocList(__AnonStruct_77eaba63dfee299d), __AnonStruct_77eaba63dfee299dRelease);
    if (T == __AnonStruct_77eaba63dfee299d) return __AnonStruct_77eaba63dfee299dRelease;
    if (T == HostCmd_execResult) return HostCmd_execResultRelease;
    if (T == CmdErrOrNonZeroExit) return CmdErrOrNonZeroExitRelease;
    if (T == HostFile_read_bytesResult) return HostFile_read_bytesResultRelease;
    if (T == RocListWith(u8, false)) return RocListSpineRelease(RocListWith(u8, false));
    if (T == HostFile_write_bytesResult) return HostFile_write_bytesResultRelease;
    @compileError("generated glue has no recursive release policy for " ++ @typeName(T));
}


// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.

pub extern fn roc_alloc(length: usize, alignment: usize) callconv(.c) ?*anyopaque;
pub extern fn roc_dealloc(ptr: *anyopaque, alignment: usize) callconv(.c) void;
pub extern fn roc_realloc(ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque;
pub extern fn roc_dbg(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_expect_failed(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_crashed(bytes: [*]const u8, len: usize) callconv(.c) void;

// Hosted Symbols
//
// The platform host must export these symbols with the exact direct C ABI signatures.
// Refcounted arguments are owned by the hosted function.

/// Hosted symbol for Host.run_graph!
/// Roc signature: { tasks : List({ action : [Cmd({ args : List(Str), program : Str })], cwd : Str, depends_on : List(U64), description : Str, env : List((Str, Str)), id : U64, inputs : List(Str), outputs : List(Str) }) } => Try({}, [BuildFailed(Str)])
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg0.decref(roc_host);
/// The result is owned by Roc: return exactly one owned reference.
pub extern fn roc_build_run_graph(arg0: HostRun_graphArgs) callconv(.c) HostRun_graphResult;

/// Hosted symbol for Host.log_info!
/// Roc signature: Str => {}
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg0.decref(roc_host);
pub extern fn roc_log_info(arg0: RocStr) callconv(.c) void;

/// Hosted symbol for Host.log_warn!
/// Roc signature: Str => {}
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg0.decref(roc_host);
pub extern fn roc_log_warn(arg0: RocStr) callconv(.c) void;

/// Hosted symbol for Host.log_error!
/// Roc signature: Str => {}
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg0.decref(roc_host);
pub extern fn roc_log_error(arg0: RocStr) callconv(.c) void;

/// Hosted symbol for Host.cmd_exec!
/// Roc signature: { args : List(Str), program : Str } => Try({}, [CmdErr(Str), NonZeroExit(I32)])
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg0.decref(roc_host);
/// The result is owned by Roc: return exactly one owned reference.
pub extern fn roc_cmd_exec(arg0: HostCmd_execArgs) callconv(.c) HostCmd_execResult;

/// Hosted symbol for Host.file_read_bytes!
/// Roc signature: Str => Try(List(U8), [IoErr(Str)])
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg0.decref(roc_host);
/// The result is owned by Roc: return exactly one owned reference.
pub extern fn roc_file_read_bytes(arg0: RocStr) callconv(.c) HostFile_read_bytesResult;

/// Hosted symbol for Host.file_write_bytes!
/// Roc signature: Str, List(U8) => Try({}, [IoErr(Str)])
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg0.decref(roc_host);
///     arg1.decref(roc_host);
/// The result is owned by Roc: return exactly one owned reference.
pub extern fn roc_file_write_bytes(arg0: RocStr, arg1: RocListWith(u8, false)) callconv(.c) HostFile_write_bytesResult;

/// Hosted symbol for Host.path_exists!
/// Roc signature: Str => Bool
/// Owned arguments. Release each exactly once before returning, unless it is
/// moved into storage or into the result:
///     arg0.decref(roc_host);
pub extern fn roc_path_exists(arg0: RocStr) callconv(.c) bool;


/// Default memory management functions for Roc platforms.
///
/// Uses `RocEnv.allocator` for allocation. Each allocation prepends
/// size metadata so that dealloc/realloc can recover the original
/// allocation size (required because `roc_dealloc` receives no length).
pub const DefaultAllocators = struct {
    /// Allocate memory for the Roc runtime.
    pub fn rocAlloc(roc_host: *RocHost, length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;
        const total_size = length + size_storage_bytes;

        const base_ptr = allocator.rawAlloc(total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_alloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Store total size immediately before the user data pointer
        const size_ptr: *usize = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes - @sizeOf(usize));
        size_ptr.* = total_size;

        return @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes);
    }

    /// Free memory previously allocated by `rocAlloc`.
    pub fn rocDealloc(roc_host: *RocHost, ptr: *anyopaque, alignment: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        const size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const total_size = size_ptr.*;

        const base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);
        const slice = base_ptr[0..total_size];
        allocator.rawFree(slice, align_enum, @returnAddress());
    }

    /// Reallocate memory, copying existing data to the new allocation.
    pub fn rocRealloc(roc_host: *RocHost, ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        // Read old size from metadata
        const old_size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const old_total_size = old_size_ptr.*;
        const old_base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);

        // Allocate new block
        const new_total_size = new_length + size_storage_bytes;
        const new_base_ptr = allocator.rawAlloc(new_total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_realloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Copy old user data to new location
        const old_user_data_size = old_total_size - size_storage_bytes;
        const copy_size = @min(old_user_data_size, new_length);
        const new_user_ptr: [*]u8 = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes);
        const old_user_ptr: [*]const u8 = @ptrCast(ptr);
        @memcpy(new_user_ptr[0..copy_size], old_user_ptr[0..copy_size]);

        // Free old allocation
        allocator.rawFree(old_base_ptr[0..old_total_size], align_enum, @returnAddress());

        // Store new size and return user pointer
        const new_size_ptr: *usize = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes - @sizeOf(usize));
        new_size_ptr.* = new_total_size;
        return new_user_ptr;
    }
};

/// Default handlers for dbg, expect-failed, and crash.
///
/// Routes output through `RocEnv.roc_io` for platform portability.
pub const DefaultHandlers = struct {
    /// Print a `dbg` expression to stderr.
    pub fn rocDbg(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC DBG] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a failed `expect` to stderr.
    pub fn rocExpectFailed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC EXPECT] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a `crash` message to stderr and terminate.
    pub fn rocCrashed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC CRASHED] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
        env.roc_io.onFatal();
    }
};

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
///
/// Example:
/// ```zig
/// var env = RocEnv{ .allocator = gpa.allocator(), .roc_io = RocIo.default() };
/// var roc_host = makeRocHost(&env);
/// ```
pub fn makeRocHost(env: *RocEnv) RocHost {
    return .{
        .env = @ptrCast(env),
        .roc_alloc = &DefaultAllocators.rocAlloc,
        .roc_dealloc = &DefaultAllocators.rocDealloc,
        .roc_realloc = &DefaultAllocators.rocRealloc,
        .roc_dbg = &DefaultHandlers.rocDbg,
        .roc_expect_failed = &DefaultHandlers.rocExpectFailed,
        .roc_crashed = &DefaultHandlers.rocCrashed,
    };
}

// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.

/// Entrypoint: main_for_host!
pub extern fn roc_main(arg0: RocList(RocStr)) callconv(.c) i32;

